(function(g){var window=this;var E1=function(a){var b={languageCode:a.i,languageName:a.l,displayName:g.zz(a),kind:a.o,name:a.u,id:a.G,is_servable:a.B,is_default:a.isDefault,is_translateable:a.C,vss_id:a.w};a.g&&(b.translationLanguage=a.g);return b},F1=function(a){return a.g?a.g.languageCode:a.i},$oa=function(a,b){var c=new g.yz;
c.i=a.i;c.l=a.l;c.u=a.u;c.o=a.o;c.isDefault=!1;c.B=a.B;c.C=a.C;c.w=a.w;c.D=a.D;c.g=b;return c},apa=function(){this.i=[];
this.g=[]},G1=function(a,b){return b?a.g.concat(a.i):a.g},H1=function(a,b){switch(b.o){case "asr":var c=a.i;
g.Ya(c,(0,g.x)(b.cq,b))||c.push(b);break;default:c=a.g,g.Ya(c,(0,g.x)(b.cq,b))||c.push(b)}},I1=function(a){g.F.call(this);
this.Xa=a;this.i=new apa;this.u=[]},J1=function(a,b,c){I1.call(this,a);
this.g=null;this.u=b.Ct;this.l=c},K1=function(){this.g=[]},L1=function(a,b,c,d,e,f){g.F.call(this);
this.G=a;this.l=b;this.R=b.L();this.u=new K1;this.g=null;this.B=d;this.I=f;this.i=this.o=null;this.M=c;this.w=e||!1;this.C=new g.J(this.Nv,1E3,this);g.H(this,this.C);this.D=new g.Ks(this);g.H(this,this.D);this.D.J(b,"SEEK_COMPLETE",this.tw);this.tw();this.Nv()},M1=function(a,b){b-=a.l.ub();
var c=a.g;a.g=g.Wa(a.M.lf(b).g);c!=a.g&&a.I&&a.I()},N1=function(a,b){var c=g.pw(g.Cw(b,a.G,{})),d={format:"RAW",
withCredentials:!0};a.w&&(d.responseType="arraybuffer");a.i=g.bq(c,d,3,100).then((0,g.x)(a.pJ,a));a.o=b;c=a.u;d=a.o.g[0].i;var e=g.pb(c.g,d);0<=e||0>e&&1==(-e-1)%2||(e=-e-1,0<e&&1==d-c.g[e-1]&&e<c.g.length&&1==c.g[e]-d?(g.db(c.g,e),g.db(c.g,e-1)):0<e&&1==d-c.g[e-1]?c.g[e-1]=d:e<c.g.length&&1==c.g[e]-d?c.g[e]=d:(g.lb(c.g,e,0,d),g.lb(c.g,e+1,0,d)))},O1=function(a,b){I1.call(this,b.L());
this.g=a;this.B=b;this.l=null;this.o=!1;this.w=g.hz(this.B.L())&&!this.g.i},P1=function(a,b){var c=[],d;
for(d in a.g.g){var e=a.g.g[d];if(g.TO(e,b||null)){var f="en",k="English",l=".en",m="";if(e=e.info.captionTrack)f=e.languageCode,k=e.displayName,l=e.vssId,m=e.kind;c.push(new g.yz({id:d,languageCode:f,languageName:k,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m}))}}return c},bpa=function(a,b){return null!=b&&b in a.g.g?a.g.g[b]:null},Q1=function(a,b,c){var d=[],e;
for(e in a.g.g){var f=a.g.g[e];if(g.TO(f,c||null)){var k=f.info.captionTrack;k&&k.languageCode==b&&d.push(f)}}return d.length?d[0]:null},R1=function(a,b,c,d,e){I1.call(this,e||null);
c=c||g.hp(a).hl||"";c=c.split("_").join("-");this.o=g.jp(a,{hl:c});this.l=b;this.w=!!d;this.B={};this.g=null},S1=function(a){if(!cpa.test(a))throw Error("'"+a+"' is not a valid hex color");
4==a.length&&(a=a.replace(dpa,"#$1$1$2$2$3$3"));a=a.toLowerCase();a=parseInt(a.substr(1),16);return[a>>16,a>>8&255,a&255]},T1=function(a,b,c,d,e,f,k){f=void 0===f?!1:f;
k=void 0===k?null:k;g.rD.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.l=f;this.g=k},U1=function(a,b,c,d,e){g.rD.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.g=[]},W1=function(a){a=void 0===a?{}:a;
var b="_"+V1++;return new U1(0,0x8000000000000,0,b,a)},Y1=function(a,b,c,d,e,f){var k={};
g.Sa(k,b);g.Sa(k,a.params);g.Sa(k,c);var l={};g.Sa(l,b.sb);a.params.sb&&g.Sa(l,a.params.sb);g.Sa(l,c.sb);k.sb=l;g.T.call(this,{A:"div",F:"caption-window",K:{id:"caption-window-"+a.id,dir:1==k.pe?"rtl":"ltr",tabindex:"0","aria-live":"assertive",lang:k.lang},H:[{A:"span",F:"captions-text",K:{style:"word-wrap: normal; display: block;"}}]});this.B=[];this.P=!1;this.o=a;this.Y=this.S=null;this.Pa=e;this.La=f;this.C=null;this.X=.96*e;this.va=.96*f;this.l=k;this.Ha=c;this.w=this.i["captions-text"];this.Ba=
null!=this.w.style["box-decoration-break"]||null!=this.w.style["-webkit-box-decoration-break"];this.W=d/360*16;this.type=0;this.ka=this.W*X1(l);a=new g.WK(this.element,!0);g.H(this,a);a.subscribe("dragstart",this.HE,this);a.subscribe("dragmove",this.GE,this);a.subscribe("dragend",this.FE,this);this.ua=this.la=0;b="";this.l.windowOpacity&&(a=S1(this.l.windowColor),b="rgba("+a[0]+","+a[1]+","+a[2]+","+this.l.windowOpacity+")");a={"background-color":b,display:!1===this.l.isVisible?"none":"","text-align":epa[this.l.textAlign]};
this.Ba&&(a["border-radius"]=b?this.ka/8+"px":"");if(this.u=2==this.o.params.pe||3==this.o.params.pe)b=this.element,c="vertical-rl",1==this.l.lz&&(c="vertical-lr"),g.Jd&&(c="vertical-lr"==c?"tb-lr":"tb-rl"),g.Yf(b,"-o-writing-mode",c),g.Yf(b,"-webkit-writing-mode",c),g.Yf(b,"writing-mode",c),g.Yf(b,"text-orientation","upright"),g.K(b,"ytp-vertical-caption"),3==this.o.params.pe&&(g.Yf(b,"text-orientation",""),g.Yf(b,"transform","rotate(180deg)"));g.Yf(this.element,a);switch(this.l.If){case 0:case 1:case 2:g.K(this.element,
"ytp-caption-window-top");break;case 6:case 7:case 8:g.K(this.element,"ytp-caption-window-bottom")}},X1=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(0==a.offset||2==a.offset)b*=.8;return b},Z1=function(a,b){var c={},d=b.background?b.background:a.l.sb.background;
if(null!=b.backgroundOpacity||b.background){var e=null!=b.backgroundOpacity?b.backgroundOpacity:a.l.sb.backgroundOpacity;d=S1(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.Ba&&(c["box-decoration-break"]="clone",c["border-radius"]=a.ka/8+"px")}if(null!=b.fontSizeIncrement||null!=b.offset)c["font-size"]=a.W*X1(b)+"px";d=1;e=b.color||a.l.sb.color;if(b.color||null!=b.textOpacity)e=S1(e),d=null==b.textOpacity?a.l.sb.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",c.color=
e,c.fill=e;var f=b.charEdgeStyle;0==f&&(f=null);if(f){e="rgba(34, 34, 34, "+d+")";var k="rgba(204, 204, 204, "+d+")";b.Kt&&(k=e=b.Kt);var l=a.W/16/2,m=Math.max(l,1),n=Math.max(2*l,1),q=Math.max(3*l,1),t=Math.max(5*l,1);d=[];switch(f){case 4:for(;q<=t;q+=l)d.push(n+"px "+n+"px "+q+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=q;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+k);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(q=0;5>q;q++)d.push("0 0 "+n+"px "+
e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.Kp()?'"Carrois Gothic SC", sans-serif-smallcaps':
'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.l.sb.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7==b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.De&&(c["font-style"]="italic");b.underline&&(c["text-decoration"]="underline");
b.CC&&(c.visibility="hidden");1==b.EC&&a.u&&(c["text-combine-upright"]="all",c["text-orientation"]="mixed",e=g.pu||g.jz,3==a.o.params.pe?c.transform=e?"rotate(90deg)":"rotate(180deg)":e&&(c.transform="rotate(-90deg)"));if(1==b.oe||2==b.oe||3==b.oe||4==b.oe||5==b.oe)if(g.pu)c["font-weight"]="bold";else switch(c["text-emphasis"]="filled circle",c["webkit-text-emphasis"]="filled circle",b.oe){case 4:case 3:c["text-emphasis-position"]="under left";c["webkit-text-emphasis-position"]="under left";break;
case 5:case 2:c["text-emphasis-position"]="over right",c["webkit-text-emphasis-position"]="over right"}return c},$1=function(a){a.C=g.Qd("SPAN");
g.Yf(a.C,{display:"block"});g.K(a.C,"caption-visual-line");a.w.appendChild(a.C)},a2=function(a,b){var c=g.Qd("SPAN");
g.Yf(c,{display:"inline-block","white-space":"pre-wrap"});g.Yf(c,Z1(a,b));c.classList.add("ytp-caption-segment");a.C.appendChild(c);c.previousElementSibling&&(g.Yf(c.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.Yf(c,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return c},b2=function(a,b,c){a.P=a.P||!!c;
var d={};g.Sa(d,a.l.sb);g.Sa(d,c||b.g);g.Sa(d,a.Ha.sb);(c=!a.C)&&$1(a);for(var e=a.S&&a.Y&&g.ac(d,a.Y)?a.S:a2(a,d),f="string"===typeof b.text,k=f?b.text.split("\n"):[b.text],l=0;l<k.length;l++){var m=0<l||!b.l,n=k[l];m&&!c?($1(a),e=a2(a,d)):m&&c&&(c=!1);n&&(e.appendChild(f?g.Rd(n):n),f||"RUBY"!=n.tagName||4!=n.childElementCount||g.pu||!g.bg(n.children[2],"text-emphasis")||(m=a.u?"padding-right":"padding-top",g.bg(n.children[2],"text-emphasis-position")&&(m=a.u?"padding-left":"padding-bottom"),g.Ld?
g.Yf(e,m,"1em"):g.Yf(e,m,"0.5em")))}a.Y=d;a.S=e;a.B.push(b)},c2=function(){},e2=function(){this.o=this.i=this.mode=this.l=0;
this.u=new d2(this);this.w=new d2(this);this.g=[];this.clear()},fpa=function(a,b,c){if(255==a&&255==b||!a&&!b)return{dl:a,
fl:b,result:0};a=f2[a];b=f2[b];if(a&128){if(!(b&128)&&0!=c.g&&c.i==b)return{dl:a,fl:b,result:1}}else if(b&128&&1<=a&&31>=a)return{dl:a,fl:b,result:2};return{dl:a,fl:b,result:3}},gpa=function(a,b,c,d){255==b&&255==c||!b&&!c?(45==++a.o&&a.reset(),a.u.g.clear(),a.w.g.clear()):(a.o=0,g2(a.u,b,c,d))},hpa=function(a,b){a.g.sort(function(e,f){var k=e.time-f.time;
return 0==k?e.order-f.order:k});
for(var c=0;c<a.g.length;c++){var d=a.g[c];a.i=d.time;0==d.type?gpa(a,d.Et,d.Ft,b):1==d.type&&a.l&496&&g2(a.w,d.Et,d.Ft,b)}a.g.length=0},h2=function(){this.g=0},i2=function(){this.i=this.l=this.g=0},j2=function(){this.timestamp=this.Qd=0},k2=function(a){this.l=[];
for(var b=0;15>=b;b++){this.l[b]=[];for(var c=0;32>=c;c++)this.l[b][c]=new j2}this.g=this.i=this.row=0;this.style=new h2;this.u=a;this.o=0},l2=function(a,b){if(3==a.style.g){for(var c=0,d=0,e=a.u.i+0,f="",k="",l=e,m=1;15>=m;++m){for(var n=!1,q=d?d:1;32>=q;++q){var t=a.l[m][q];
if(0!=t.Qd){0==c&&(c=m,d=q);n=String.fromCharCode(t.Qd);var v=t.timestamp;v<e&&(e=v);t.timestamp=l;k&&(f+=k,k="");f+=n;n=!0}if((0==t.Qd||32==q)&&n){k="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.u(c,d,e,l,f)}else for(d=c=0,f=e=a.u.i+0,k=1;15>=k;++k)for(l="",m=1;32>=m;++m)if(q=a.l[k][m],t=q.Qd,0!=t&&(0==c&&(c=k,d=m),n=String.fromCharCode(t),v=q.timestamp,v<=e&&(e=v),l+=n,q.reset()),32==m||0==t)l&&b.u(c,d,e,f,l),e=f,l="",d=c=0},mpa=function(a,b){switch(a){case 0:return ipa[(b&127)-32];
case 1:return jpa[b&15];case 2:return kpa[b&31];case 3:return lpa[b&31]}return 0},m2=function(a){return a.l[a.row][a.i]},n2=function(a,b,c){2<=b&&1<a.i&&(--a.i,m2(a).Qd=0);
var d=m2(a);d.timestamp=a.u.i+0;d.Qd=mpa(b,c);32>a.i&&a.i++},o2=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++)a.l[b+e][f].Rf(a.l[c+e][f])},p2=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.l[b+d][e].reset()},q2=function(a){a.row=0<a.g?a.g:1;
a.i=1;p2(a,0,15)},r2=function(a){this.o=a;
this.u=0;this.style=new h2;this.w=new k2(a);this.B=new k2(a);this.C=new k2(a);this.i=this.w;this.l=this.B;this.g=this.i},s2=function(a,b,c){var d=a.i,e=!1;
switch(a.style.get()){case 4:if(0<d.g)break;case 1:case 2:l2(d,c),q2(a.i),q2(a.l),d.row=15,d.g=b,e=!0}a.style.set(3);a.g=d;a.g.style=a.style;a.o.mode=1<<d.o;e?d.i=1:d.g!=b&&(d.g>b?(l2(d,c),p2(d,d.row-d.g,b)):d.row<b&&(b=d.g),d.g=b)},t2=function(a){a.style.set(1);
a.g=a.l;a.g.g=0;a.g.style=a.style;a.o.mode=1<<a.g.o},u2=function(a){a.style.set(4);
a.g=a.C;a.g.style=a.style;a.o.mode=1<<a.g.o},d2=function(a){this.i=a;
this.g=new i2;this.u=0;this.l=new r2(a);this.w=new r2(a);this.o=this.l},g2=function(a,b,c,d){a.g.update();
b=fpa(b,c,a.g);switch(b.result){case 0:return;case 1:case 2:return}var e=b.dl;c=b.fl;if(32<=e||!e)a.i.mode&a.i.l&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.o.g,b&96&&n2(a,0,b),c&96&&n2(a,0,c),0!=b&&0!=c&&3==a.style.g&&l2(a,d));else if(e&16)a:if(!a.g.matches(e,c)&&(b=a.g,b.l=e,b.i=c,b.g=2,b=e&8?a.w:a.l,a.o=b,a.i.mode=1<<(a.u<<2)+(b.u<<1)+(4==b.style.g?1:0),(a.i.mode|1<<(a.u<<2)+(b.u<<1)+(4!=b.style.g?1:0))&a.i.l))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];a=c&16?4*((c&14)>>1):
0;c=b.g;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!=c.row){if(d<c.g&&(d=c.g,d==c.row))break;var f=1+c.row-c.g,k=1+d-c.g;o2(c,k,f,c.g);b=f;e=c.g;k<f?(f=k+e-f,0<f&&(b+=f,e-=f)):(f=f+e-k,0<f&&(e-=f));p2(c,b,e)}}c.row=d;c.i=a+1}else switch(e&7){case 1:switch(c&112){case 32:n2(b.g,0,32);break a;case 48:57==c?(d=b.g,m2(d).Qd=0,32>d.i&&d.i++):n2(b.g,1,c&15)}break;case 2:c&32&&n2(b.g,2,c&31);break;case 3:c&32&&n2(b.g,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:t2(b);break;case 33:d=
b.g;1<d.i&&(--d.i,m2(d).Qd=0);break;case 36:d=b.g;b=m2(d);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(d.l[a][c]==b){for(;32>=c;c++)d.l[a][c].reset();break}break;case 37:s2(b,2,d);break;case 38:s2(b,3,d);break;case 39:s2(b,4,d);break;case 40:n2(b.g,0,32);break;case 41:b.style.set(2);b.g=b.i;b.g.g=0;b.g.style=b.style;b.o.mode=1<<b.g.o;break;case 42:d=b.C;d.g=15;d.style.set(4);q2(d);u2(b);break;case 43:u2(b);break;case 44:a=b.i;switch(b.style.get()){case 1:case 2:case 3:l2(a,d)}p2(a,0,15);break;case 45:b:{a=
b.g;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.i=1;break b}case 3:}2>a.g&&(a.g=2,a.row<a.g&&(a.row=a.g));b=a.row-a.g+1;l2(a,d);o2(a,b,b+1,a.g-1);p2(a,a.row,1)}break;case 46:p2(b.l,0,15);break;case 47:l2(b.i,d),b.l.updateTime(b.o.i+0),d=b.l,b.l=b.i,b.i=d,t2(b)}break;case 7:switch(c){case 33:case 34:case 35:d=b.g,32<(d.i+=c&3)&&(d.i=32)}}},v2=function(a,b,c,d,e,f,k){var l=f[0],m=k[l.getAttribute("p")];
if(1==m.Xc){var n=f[1],q=f[2],t=f[3];l.getAttribute("p");var v=g.Kp();l.getAttribute("t");n.getAttribute("t");q.getAttribute("t");t.getAttribute("t");f=v?g.Qd("DIV"):g.Qd("RUBY");l=l.textContent;var y=g.Qd("SPAN");y.textContent=l;f.appendChild(y);n.getAttribute("p");y=v?g.Qd("DIV"):g.Qd("RP");l=n.textContent;y.textContent=l;f.appendChild(y);k=k[q.getAttribute("p")];l=q.textContent;q=v?g.Qd("DIV"):g.Qd("RT");q.textContent=l;f.appendChild(q);l=k.Xc;if(10==l||11==l||12==l||13==l||14==l)if(g.Yf(q,"text-emphasis",
"filled circle"),g.Yf(q,"webkit-text-emphasis","filled circle"),k.Xc==k.Xc==11||13==k.Xc)g.Yf(q,"webkit-text-emphasis-position","under left"),g.Yf(q,"text-emphasis-position","under left");q=!0;if(4==k.Xc||7==k.Xc||12==k.Xc||14==k.Xc)g.Yf(f,"ruby-position","over"),g.Yf(f,"-webkit-ruby-position","before");else if(5==k.Xc||6==k.Xc||11==k.Xc||13==k.Xc)g.Yf(f,"ruby-position","under"),g.Yf(f,"-webkit-ruby-position","after"),q=!1;t.getAttribute("p");l=t.textContent;t=v?g.Qd("DIV"):g.Qd("RP");t.textContent=
l;f.appendChild(t);v&&(v=q,g.Yf(f,{display:"inline-block",position:"relative"}),t=f.firstElementChild.nextElementSibling,g.Yf(t,"display","none"),t=t.nextElementSibling,g.Yf(t,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",left:"50%",transform:"translateX(-50%)",width:"400%"}),g.Yf(f.lastElementChild,"display","none"),v?(g.Yf(f,"padding-top","0.6em"),g.Yf(t,"top","0")):(g.Yf(f,"padding-bottom","0.6em"),g.Yf(t,"bottom","0")));return new T1(a,b,e,c,f,d,m)}switch(m.Xc){case 9:case 10:m.oe=
1;break;case 11:m.oe=2;break;case 12:m.oe=3;break;case 13:m.oe=4;break;case 14:m.oe=5}return new T1(a,b,e,c,l.textContent||"",d,m)},w2=function(){g.F.apply(this,arguments)},x2=function(a){w2.call(this);
this.l={};this.D={};this.G={};this.u="_"+V1++;this.w=a;this.C={};this.i=this.g=null;this.B=!0},y2=function(a,b){var c=a.getAttribute(b);
if(null!=c)return parseFloat(c)},z2=function(a,b){var c=a.getAttribute(b);
if(null!=c)return"1"==c},A2=function(a,b){var c=y2(a,b);
return void 0!=c?c:null},C2=function(a,b){var c=a.getAttribute(b);
if(null!=c)return B2.test(c),c},D2=function(a,b){var c={},d=b.getAttribute("ws");
g.Sa(c,d?a.G[d]:a.w);d=A2(b,"mh");null!=d&&(c.Up=d);d=A2(b,"ju");null!=d&&(c.textAlign=d);d=A2(b,"pd");null!=d&&(c.pe=d);d=A2(b,"sd");null!=d&&(c.lz=d);d=C2(b,"wfc");null!=d&&(c.windowColor=d);d=y2(b,"wfo");void 0!=d&&(c.windowOpacity=d/255);return c},E2=function(a,b){var c={},d=b.getAttribute("wp");
d&&g.Sa(c,a.D[d]);d=A2(b,"ap");null!=d&&(c.If=d);d=y2(b,"cc");null!=d&&(c.vl=d);d=y2(b,"ah");null!=d&&(c.Ee=d);d=y2(b,"rc");null!=d&&(c.ik=d);d=y2(b,"av");null!=d&&(c.ug=d);return c},F2=function(a,b,c,d){var e={};
g.Sa(e,E2(a,b));g.Sa(e,D2(a,b));d?g.ac(e,a.w)?(d=a.u,e=a.w):d="_"+V1++:d=b.getAttribute("id")||"_"+V1++;a=y2(b,"t")+c;b=y2(b,"d")||0x8000000000000;if(2==e.pe||3==e.pe)c=e.ik,e.ik=e.vl,e.vl=c;return new U1(a,b,0,d,e)},G2=function(a,b,c,d,e,f,k){Y1.call(this,a,b,c,d,e,f,k);
this.type=1},H2=function(a,b,c){this.B=c;
this.version=this.w=this.o=this.g=0;this.i=new DataView(a);this.l=[]},I2=function(a){var b=a.g;
a.g+=1;return a.i.getUint8(b)},J2=function(a){var b=a.g;
a.g+=4;return a.i.getUint32(b)},K2=function(a,b){w2.call(this);
this.i=a;this.track="CC3"==b.l?4:0;this.g=new e2;this.g.l=1<<this.track},M2=function(a){if("string"===typeof a)return!1;
a=new H2(a,8,0);return L2(a)},L2=function(a){if(!(a.g<a.i.byteLength)||1380139777!=J2(a))return!1;
a.version=I2(a);if(1<a.version)return!1;I2(a);I2(a);I2(a);return!0},N2=function(a,b,c,d,e,f,k){Y1.call(this,a,b,c,d,e,f,k);
g.K(this.element,"ytp-caption-window-rollup");this.type=2;this.D=[];this.I=this.G=this.da=0;this.M=NaN;this.wa=0;this.Ca=null;this.ca=new g.J(this.uJ,433,this);g.H(this,this.ca);g.Yf(this.element,"overflow","hidden")},npa=function(a,b){return(a.u?b.offsetHeight:b.offsetWidth)+1},opa=function(a){if(isNaN(a.M)){var b=a.l.vl;
if(b){var c=g.Qd("SPAN");g.$d(c,"\u2013".repeat(b));g.Yf(c,Z1(a,a.l.sb));a.w.appendChild(c);a.M=c.offsetWidth;a.w.removeChild(c)}else a.M=0}return a.M},ppa=function(a,b){if(!b)return"";
a.u&&1!=a.o.params.lz&&(b*=-1);return"translate"+(a.u?"X":"Y")+"("+b+"px)"},O2=function(a){a.D=[].concat(g.ea(document.getElementsByClassName("caption-visual-line")));
for(var b=a.o.params.ik,c=0,d=0,e=a.D.length-1;c<b&&-1<e;){var f=a.D[e];d+=a.u?f.offsetWidth:f.offsetHeight;c++;e--}a.D.length<b&&(d*=b/a.D.length);a.G=d;a.I=Math.max(opa(a),a.wa,npa(a,a.w))},qpa=function(a,b){O2(a);
var c=a.D.reduce(function(e,f){return(a.u?f.offsetWidth:f.offsetHeight)+e},0);
c=a.G-c;if(c!=a.da){var d=0<c&&0==a.da;b||isNaN(c)||d||(g.K(a.element,"ytp-rollup-mode"),g.cn(a.ca));g.Yf(a.w,"transform",ppa(a,c));a.da=c}O2(a)},P2=function(){w2.call(this)},Q2=function(a,b,c,d,e,f,k,l,m){switch(k.tagName){case "b":l.bold=!0;
break;case "i":l.De=!0;break;case "u":l.underline=!0}for(var n=0;n<k.childNodes.length;n++){var q=k.childNodes[n];if(3==q.nodeType){q=new T1(b,c,d,e.id,q.nodeValue,f||0<n,g.Zb(l)?void 0:l);m.push(q);var t=e;g.H(t,q);t.g.push(q)}else t={},g.Sa(t,l),Q2(a,b,c,d,e,!0,q,t,m)}},R2=function(a){var b=0;
a=g.p(a.split(":"));for(var c=a.next();!c.done;c=a.next())b=60*b+parseFloat(c.value);return 1E3*b},S2=function(a,b,c,d){d=Object.assign({Up:0},d);
return new U1(a,b,c,"_"+V1++,d)},T2=function(a){g.F.call(this);
this.i=a;this.g=null},W2=function(a){g.SO.call(this,a);
this.l=a.L();this.O=a.getVideoData();this.la=g.eK(a);this.M=a;var b=null,c=g.Qn("yt-html5-player-modules::subtitlesModuleData");c&&(b=new g.An(c));this.aa=b;this.o={sb:{}};this.w={sb:{}};this.G=[];this.R={};this.S={};this.I=!1;this.ca=g.UO(this.O,this.M);this.ua=!!this.O.captionTracks.length;this.va=!!this.O.Si;this.X="3"==this.l.l;b=a.app.u;c=!(!b||!b.xk());this.ka=!(!b||!b.ph());this.u=this.X&&c&&!this.ca;this.D=!this.u&&this.X&&this.ka&&this.ca;this.i=this.B=this.C=this.P=this.ma=null;this.Y=new T2(this.l);
g.H(this,this.Y);c=b=this.g=null;this.u||(b=new g.$m(this.Cz,void 0,this),g.H(this,b),c=new g.J(this.VK,2E3,this),g.H(this,c));this.W=b;this.da=c;this.ba=new g.Ks(this);g.H(this,this.ba);this.u||this.ba.J(a,"resize",this.Or);this.ba.J(a,"onPlaybackAudioChange",this.VG);this.ba.J(a,g.uD("captions"),this.JD,this);this.ba.J(a,"crx_captions",this.KD,this);U2(this,V2(this,"display-settings")||{})},X2=function(a){if(1==a.l.Nf||1==a.O.Nf||"alwayson"==g.gC(a.O,"yt:cc"))return!0;
if(2==a.l.Nf){var b=V2(a,"module-enabled");if(null!=b)return!!b}if(a.O.captionTracks.length)var c=a.player.getAudioTrack().zo;return"ON"==c||"on"==g.gC(a.O,"yt:cc")},Y2=function(a,b){if(a.g&&(void 0===b||!b)||!a.O.captionTracks.length)return!1;
var c=a.player.getAudioTrack();return!!c.Fl||"FORCED_ON"==c.zo},$2=function(a,b){if(a.i){if(a.B&&a.B.g)return a.B.g;
var c=b;c||(c=a.va?!1:a.ua?!1:!0);c=G1(a.i.i,c);for(var d=[a.O.Mf,a.l.Mf,g.gC(a.O,"yt:cc_default_lang")],e=0;e<d.length;e++)for(var f=0;f<c.length;f++)if(F1(c[f])==d[e])return c[f];return a.B&&a.B.Jo?a.B.Jo:(d=c.find(function(k){return k.isDefault}))?d:c[0]||Z2(a)}return null},Z2=function(a){return a.B&&a.B.Fl},a3=function(a){var b=Z2(a);
return!!b&&a.g==b},b3=function(a,b){for(var c=a.M.app.u.Za().textTracks,d=a.g.toString(),e=0;e<c.length;e++){var f=c[e];
f.id==d&&(b?"showing"!=f.mode&&(f.mode="showing"):"showing"==f.mode&&(f.mode="disabled"))}},d3=function(a,b,c){a.loaded&&a.unload();
null!=c&&(a.I=c,a.I&&c3(a,"module-enabled",!!b));a.g=b;Y2(a)&&(a.g=Z2(a));a.load()},rpa=function(a,b){var c=a.la.getVideoContentRect(!0).height;
if(!c)return null;var d=a.la.getPlayerSize();switch(null!=b.params.Up?b.params.Up:1<b.g.length?1:0){case 1:return new G2(b,a.o,a.w,c,d.width,d.height,a.l.experiments);case 2:return new N2(b,a.o,a.w,c,d.width,d.height,a.l.experiments);default:return new Y1(b,a.o,a.w,c,d.width,d.height,a.l.experiments)}},U2=function(a,b,c){var d=e3.sb;
a.o={};g.Sa(a.o,e3);a.o.sb={};g.Sa(a.o.sb,d);a.w={sb:{}};var e=b.backgroundOverride?a.w:a.o,f=b.background||d.background;B2.test(f);e.sb.background=f;e=b.colorOverride?a.w:a.o;f=b.color||d.color;B2.test(f);e.sb.color=f;e=b.windowColorOverride?a.w:a.o;f=b.windowColor||e3.windowColor;B2.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.w:a.o;f=b.backgroundOpacity;null==f&&(f=d.backgroundOpacity);e.sb.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.w:a.o;f=b.fontSizeIncrement;null==f&&(f=d.fontSizeIncrement);
e.sb.fontSizeIncrement=f;f=b.fontStyleOverride?a.w:a.o;e=b.fontStyle;null==e&&(e=d.bold&&d.De?3:d.bold?1:d.De?2:0);f=f.sb;switch(e){case 1:f.bold=!0;delete f.De;break;case 2:delete f.bold;f.De=!0;break;case 3:f.bold=!0;f.De=!0;break;default:delete f.bold,delete f.De}e=b.textOpacityOverride?a.w:a.o;f=b.textOpacity;null==f&&(f=d.textOpacity);e.sb.textOpacity=f;e=b.windowOpacityOverride?a.w:a.o;f=b.windowOpacity;null==f&&(f=e3.windowOpacity);e.windowOpacity=f;e=b.charEdgeStyleOverride?a.w:a.o;f=b.charEdgeStyle;
null==f&&(f=d.charEdgeStyle);e.sb.charEdgeStyle=f;e=b.fontFamilyOverride?a.w:a.o;f=b.fontFamily;null==f&&(f=d.fontFamily);e.sb.fontFamily=f;a.loaded&&a.Or();c&&c3(a,"display-settings",b)},g3=function(a,b){if(b&&!a.C){var c=W1({pe:0,
lang:"en"});a.C=[c,new T1(c.start,c.end-c.start,0,c.id,"Captions look like this")];g.rK(a.player,a.C)}else!b&&a.C&&(f3(a,a.C),a.C=null)},f3=function(a,b){g.tS(a.player.app,b,void 0);
(0,g.z)(b,function(c){g.eb(this.G,c)},a);
a.W.mj()},V2=function(a,b){if(!a.aa)return null;
try{var c=a.aa.get(b)}catch(d){a.aa.remove(b)}return c},c3=function(a,b,c){if(a.aa)try{a.aa.set(b,c)}catch(d){}};
g.yz.prototype.cq=g.ca(11,function(a){return a?this.toString()==a.toString():!1});
g.Ou.prototype.Rl=g.ca(10,function(a){return(a=this.Wf(a))?a.i:0});
g.Vw.prototype.Rl=g.ca(9,function(){return 0});
g.pt.prototype.Ui=g.ca(8,function(){for(var a=g.Cd(document,"track",void 0,this.g),b=0;b<a.length;b++)g.Vd(a[b])});
g.EQ.prototype.Ui=g.ca(7,function(){this.g.Ui()});
g.pt.prototype.xk=g.ca(6,function(){return!!this.g.textTracks});
g.EQ.prototype.xk=g.ca(5,function(){return this.g.xk()});
g.pt.prototype.Mi=g.ca(4,function(a){for(var b=0;b<a.length;b++)this.g.appendChild(a[b])});
g.EQ.prototype.Mi=g.ca(3,function(a){this.g.Mi(a)});
g.gt.prototype.ph=g.ca(2,function(){});
g.pt.prototype.ph=g.ca(1,function(){return!(!this.g.textTracks||!this.g.textTracks.addEventListener)});
g.EQ.prototype.ph=g.ca(0,function(){return this.g.ph()});
var spa=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Adlm|Arab|Hebr|Nkoo|Rohg|Thaa))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i,B2=/^#(?:[0-9a-f]{3}){1,2}$/i;g.r(I1,g.F);I1.prototype.ny=function(){return!1};
I1.prototype.V=function(){this.vg();g.F.prototype.V.call(this)};
g.r(J1,I1);J1.prototype.Sp=function(a,b,c){b=this.lj(a,b);var d=(0,g.x)(function(e){this.g=null;c(e.responseText,a)},this);
this.vg();this.g=g.Bp(b,{format:"RAW",onSuccess:d,withCredentials:!0})};
J1.prototype.Tp=function(a){if(this.l)for(var b=g.p(this.l.captionTracks),c=b.next();!c.done;c=b.next())H1(this.i,c.value);a()};
J1.prototype.lj=function(a,b){var c=a.D,d={fmt:b};if("srv3"==b||"3"==b)g.Kp()?Object.assign(d,{xorb:2,xobt:1,xovt:1}):Object.assign(d,{xorb:2,xobt:3,xovt:3});a.g&&(d.tlang=F1(a));return g.jp(c,d)};
J1.prototype.vg=function(){this.g&&this.g.abort()};
K1.prototype.contains=function(a){a=g.pb(this.g,a);return 0<=a||0>a&&1==(-a-1)%2};
K1.prototype.length=function(){return this.g.length/2};
g.r(L1,g.F);g.h=L1.prototype;g.h.V=function(){g.F.prototype.V.call(this);this.i&&this.i.cancel()};
g.h.tw=function(){M1(this,this.l.getCurrentTime())};
g.h.reset=function(){this.u=new K1;this.i&&(this.i.cancel(),this.i=null)};
g.h.Nv=function(){var a;if(a=null!==this.g)a=this.g,a=a.g.xf(a);!a||this.i||this.g&&30<this.g.startTime-this.l.getCurrentTime()||(a=this.g,a=a.g.Yh(a),a.g[0].duration?(this.u.contains(a.g[0].i)||N1(this,a),this.g=g.Wa(a.g)):!g.P(this.R.experiments,"force_caption_seek_for_live_killswitch")&&this.g&&this.g.u&&this.g.u+this.l.ub()<this.l.getCurrentTime()&&M1(this,this.l.getCurrentTime()));this.C.start()};
g.h.pJ=function(a){var b=!(this.w?a.response:a.responseText)||400<=a.status,c=g.$w(a);c?(a=g.Cw(this.o,this.G,{}),b=this.o,g.xw(b.i,a,c),b.requestId=a.get("req_id"),N1(this,this.o)):(b||null===this.B||(c=this.o.g[0],this.w?this.B(a.response,1E3*(c.startTime+this.l.ub())):this.B(a.responseText,1E3*(c.startTime+this.l.ub()))),this.i=this.o=null)};
g.r(O1,I1);g.h=O1.prototype;g.h.Sp=function(a,b,c){this.vg();b=bpa(this,a.getId());b||(b=a.i,b=this.g.i?Q1(this,b,"386"):Q1(this,b));if(b){var d=1E3*(b.index.Rl(b.index.je())-b.index.Ic(b.index.je()));this.l=new L1(new g.rw,this.B,b,function(e,f){c(e,a,f,d)},this.w||g.ws(b.info),(0,g.x)(function(){this.l&&this.l.reset();
this.o=!0},this))}};
g.h.ny=function(){var a=this.o;this.o=!1;return a};
g.h.Tp=function(a){var b;this.w?b=[new g.yz({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.yz({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]:b=this.g.i?P1(this,"386"):P1(this);b=g.p(b);for(var c=b.next();!c.done;c=b.next())H1(this.i,c.value);a()};
g.h.vg=function(){this.l&&(this.l.dispose(),this.l=null)};
g.h.lj=function(){return""};
g.r(R1,I1);R1.prototype.Sp=function(a,b,c){b=this.lj(a,b);var d=(0,g.x)(function(e){this.g=null;c(e.responseText,a)},this);
this.vg();this.g=g.Bp(b,{format:"RAW",onSuccess:d,withCredentials:!0})};
R1.prototype.Tp=function(a){var b=this.o,c={type:"list",tlangs:1,v:this.l,vssids:1};this.w&&(c.asrs=1);b=g.jp(b,c);c=(0,g.x)(function(d){this.g=null;if((d=d.responseXML)&&d.firstChild){for(var e=g.p(d.getElementsByTagName("track")),f=e.next();!f.done;f=e.next()){var k=f.value;f=k.getAttribute("lang_code");var l=k.getAttribute("lang_translated"),m=k.getAttribute("name"),n=k.getAttribute("kind"),q=k.getAttribute("id"),t="true"==k.getAttribute("lang_default"),v="true"==k.getAttribute("cantran");k=k.getAttribute("vss_id");
H1(this.i,new g.yz({languageCode:f,languageName:l,name:m,kind:n,id:q,is_servable:!0,is_translateable:v,vss_id:k,is_default:t}))}d=d.getElementsByTagName("target");e=d.length;for(f=0;f<e;f++)l=d[f].getAttribute("lang_code"),m=d[f].getAttribute("lang_translated"),n=d[f].getAttribute("lang_original"),q=d[f].getAttribute("id"),t="true"==d[f].getAttribute("lang_default"),l={languageCode:l,languageName:m,languageOriginal:n,id:q,isDefault:t},this.B[l.languageCode]=l.languageName,this.u.push(l)}a()},this);
this.vg();this.g=g.Bp(b,{format:"RAW",onSuccess:c,withCredentials:!0})};
R1.prototype.lj=function(a,b){var c=this.o,d={v:this.l,type:"track",lang:a.i,name:a.getName(),kind:a.o,fmt:b};a.g&&(d.tlang=F1(a));return c=g.jp(c,d)};
R1.prototype.vg=function(){this.g&&this.g.abort()};
var dpa=/#(.)(.)(.)/,cpa=/^#(?:[0-9a-f]{3}){1,2}$/i;var epa=["left","right","center","justify"];var e3={windowColor:"#080808",windowOpacity:0,textAlign:2,If:7,Ee:50,ug:100,sb:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.r(T1,g.rD);T1.prototype.toString=function(){return g.rD.prototype.toString.call(this)};g.r(U1,g.rD);U1.prototype.toString=function(){return g.rD.prototype.toString.call(this)};
var V1=0;g.r(Y1,g.T);g.h=Y1.prototype;g.h.HE=function(a,b){var c=g.qg(this.element,this.element.parentElement);this.la=a-c.x;this.ua=b-c.y;g.K(this.element,"ytp-dragging")};
g.h.GE=function(a,b){var c=g.tg(this.element),d=a-this.la-.02*this.Pa,e=b-this.ua-.02*this.La,f=(d+c.width/2)/this.X*3;f=Math.floor(g.nd(f,0,2));var k=(e+c.height/2)/this.va*3;k=Math.floor(g.nd(k,0,2));var l=f+3*k;d=(d+f/2*c.width)/this.X;d=100*g.nd(d,0,1);c=(e+k/2*c.height)/this.va;c=100*g.nd(c,0,1);this.o.params.If=l;this.o.params.ug=c;this.o.params.Ee=d;this.l.If=l;this.l.ug=c;this.l.Ee=d;this.Ny()};
g.h.FE=function(){g.mn(this.element,"ytp-dragging")};
g.h.Ny=function(){this.lh(this.B)};
g.h.lh=function(a){var b=Math.min(this.Eu(),this.X),c=this.Du(),d="";3==this.o.params.pe&&(d="rotate(180deg)");g.Yf(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.no(a);a={transform:d,top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var e=.96*this.l.Ee+2;d=this.l.If;switch(d){case 0:case 3:case 6:a.left=e+"%";break;case 1:case 4:case 7:a.left=e+"%";e=this.w.offsetWidth;
b||e?(b=b||e+1,a.width=b+"px",a["margin-left"]=b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=100-e+"%"}b=.96*this.l.ug+2;switch(d){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.element.clientHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-b+"%"}g.Yf(this.element,a)};
g.h.no=function(a){var b;for(b=0;b<a.length&&a[b]==this.B[b];b++);if(this.P||this.B.length>b)b=0,this.P=!1,this.B=[],this.C=this.Y=this.S=null,g.Td(this.w);for(;b<a.length;b++)b2(this,a[b])};
g.h.Eu=function(){return 0};
g.h.Du=function(){return 0};
g.h.toString=function(){return g.T.prototype.toString.call(this)};c2.prototype.u=function(){};e2.prototype.clear=function(){this.o=this.i=this.mode=0;this.g=[];this.reset()};
e2.prototype.reset=function(){this.mode=0;this.u.reset(0);this.w.reset(1)};
var f2=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];h2.prototype.set=function(a){this.g=a};
h2.prototype.get=function(){return this.g};
i2.prototype.clear=function(){this.g=0};
i2.prototype.update=function(){this.g=2==this.g?1:0};
i2.prototype.matches=function(a,b){return 0!=this.g&&a==this.l&&b==this.i};
j2.prototype.Rf=function(a){this.Qd=a.Qd;this.timestamp=a.timestamp};
j2.prototype.reset=function(){this.timestamp=this.Qd=0};
k2.prototype.updateTime=function(a){for(var b=1;15>=b;++b)for(var c=1;32>=c;++c)this.l[b][c].timestamp=a};
k2.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.l[b][c];a=0==d.Qd?a+"_":a+String.fromCharCode(d.Qd)}a+="\n"}return a};
k2.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.l[b][c].reset();this.o=a;this.g=0;this.i=this.row=1};
var ipa=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],jpa=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],kpa=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],lpa=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];r2.prototype.reset=function(a,b){this.u=b;this.style.set(2);this.i=this.w;this.l=this.B;this.g=this.i;var c=(a<<2)+(b<<1);this.w.reset(c);this.B.reset(c);this.C.reset((a<<2)+(b<<1)+1)};
d2.prototype.reset=function(a){this.u=a;this.g.clear();this.o=this.l;this.l.reset(a,0);this.w.reset(a,1)};g.r(w2,g.F);w2.prototype.reset=function(){};g.r(x2,w2);x2.prototype.reset=function(){this.C={};this.i=this.g=null;this.B=!0};
x2.prototype.o=function(a,b){var c=a.firstChild;c.getAttribute("format");b=b||0;Number.isFinite(b);c=Array.from(c.childNodes);c=g.p(c);for(var d=c.next();!d.done;d=c.next())if(d=d.value,1==d.nodeType)switch(d.tagName){case "head":var e=d;break;case "body":var f=d}if(e)for(e=Array.from(e.childNodes),e=g.p(e),c=e.next();!c.done;c=e.next())if(c=c.value,1==c.nodeType)switch(c.tagName){case "pen":d=c.getAttribute("id");var k=this.l,l={},m=c.getAttribute("p");m&&g.Sa(l,this.l[m]);m=z2(c,"b");null!=m&&(l.bold=
m);m=z2(c,"i");null!=m&&(l.De=m);m=z2(c,"u");null!=m&&(l.underline=m);m=A2(c,"et");null!=m&&(l.charEdgeStyle=m);m=A2(c,"of");null!=m&&(l.offset=m);m=C2(c,"bc");null!=m&&(l.background=m);m=C2(c,"ec");null!=m&&(l.Kt=m);m=C2(c,"fc");null!=m&&(l.color=m);m=A2(c,"fs");null!=m&&0!=m&&(l.fontFamily=m);m=y2(c,"sz");void 0!=m&&(l.fontSizeIncrement=m/100-1);m=y2(c,"bo");void 0!=m&&(l.backgroundOpacity=m/255);m=y2(c,"fo");void 0!=m&&(l.textOpacity=m/255);m=A2(c,"rb");null!=m&&10!=m&&0!=m&&(l.Xc=10<m?m-1:m);
m=A2(c,"hg");null!=m&&(l.EC=m);c=A2(c,"te");null!=c&&(2==c&&(l.bold=!1,c=1),l.oe=c);k[d]=l;break;case "ws":d=c.getAttribute("id");this.G[d]=D2(this,c);break;case "wp":d=c.getAttribute("id"),this.D[d]=E2(this,c)}if(f){e=b;c=[];f=Array.from(f.childNodes);f=g.p(f);for(d=f.next();!d.done;d=f.next())if(d=d.value,1==d.nodeType)switch(d.tagName){case "w":this.g=F2(this,d,e,!1);g.H(this,this.g);(d=this.C[this.g.id])&&d.end>this.g.start&&(d.end=this.g.start);this.C[this.g.id]=this.g;c.push(this.g);break;case "p":var n=
e;k=[];l=d.getAttribute("w")||this.u;m=!!z2(d,"a");n=(y2(d,"t")||0)+n;var q=y2(d,"d")||5E3;m||(!this.B&&this.i&&this.i.windowId==l&&this.i.end>n&&(this.i.end=n),this.i&&"\n"==this.i.text&&(this.i.text=""));var t=m?6:5,v=this.l[d.getAttribute("p")],y=[].concat(g.ea(d.childNodes));y.length&&(this.B=null!=d.getAttribute("d"));for(var B=0;B<y.length;B++){var C=y[B],G=void 0;0<B&&(m=!0);var I=void 0;1==C.nodeType&&(I=C);if(I&&"s"==I.tagName){if((C=this.l[I.getAttribute("p")])&&C.Xc&&(1==C.Xc?(C=y.slice(B,
B+4),4==C.length&&(G=v2(n,q,l,m,t,C,this.l),B+=3)):G=v2(n,q,l,m,t,[I],this.l)),!G){var E=I;G=n;I=q;C=l;var M=m,Y=t,ia=E.textContent?E.textContent:"",Ia=this.l[E.getAttribute("p")];E=y2(E,"t")||0;G=new T1(G+E,I-E,Y,C,ia,M,Ia)}}else G=new T1(n,q,t,l,C.textContent||"",m,v);k.push(G);this.i=G}if(0<k.length)for(k[0].windowId==this.u&&(this.g=F2(this,d,e,!0),g.H(this,this.g),c.push(this.g)),d=g.p(k),k=d.next();!k.done;k=d.next())k=k.value,k.windowId=this.g.id,l=this.g,g.H(l,k),l.g.push(k),c.push(k)}e=c}else e=
[];return e};g.r(G2,Y1);G2.prototype.no=function(a){var b=this.o.g;Y1.prototype.no.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.g==e)var d=f;else{d={};g.Sa(d,c.g);g.Sa(d,tpa);var e=c.g;var f=d}b2(this,c,d)}};
var tpa={CC:!0};g.r(H2,c2);H2.prototype.u=function(a,b,c,d,e){if(c<d){var f="_"+V1++;c=c/1E3-this.B;d=d/1E3-this.B;a=new U1(c,d-c,5,f,{textAlign:0,If:0,Ee:2.5*b,ug:5.33*a});e=new T1(c,d-c,5,f,e);this.l.push(a);this.l.push(e)}};
g.r(K2,w2);K2.prototype.o=function(a){a=new H2(a,a.byteLength,this.i);if(L2(a)){for(;a.g<a.i.byteLength;)for(0==a.version?a.o=J2(a)*(1E3/45):1==a.version&&(a.o=4294967296*J2(a)+J2(a)),a.w=I2(a);0<a.w;a.w--){var b=I2(a),c=I2(a),d=I2(a);b&4&&(b&3)==this.track&&(0==this.track||1==this.track)&&(b=this.g,b.g.push({time:a.o,type:this.track,Et:c,Ft:d,order:b.g.length}))}hpa(this.g,a);return a.l}return[]};
K2.prototype.reset=function(){this.g.clear()};g.r(N2,Y1);g.h=N2.prototype;g.h.Ny=function(){g.dn(this.ca)};
g.h.uJ=function(){g.mn(this.element,"ytp-rollup-mode");this.lh(this.Ca,!0)};
g.h.Du=function(){return this.u?this.I:this.G};
g.h.Eu=function(){return this.u?this.G:this.I};
g.h.lh=function(a,b){this.Ca=a;if(this.o.params.ik){for(var c=0,d=0;d<this.B.length&&c<a.length;d++)this.B[d]==a[c]&&c++;0<c&&c<a.length&&(a=this.B.concat(a.slice(c)));this.wa=this.I;this.G=this.I=0;Y1.prototype.lh.call(this,a);qpa(this,b);Y1.prototype.lh.call(this,a)}else Y1.prototype.lh.call(this,a)};g.r(P2,w2);
P2.prototype.o=function(a,b){for(var c=[],d=a.split(upa),e=1;e<d.length;e++){var f=d[e],k=b;if(""!=f&&!vpa.test(f)){var l=h3.exec(f);if(l&&4<=l.length){var m=R2(l[1]),n=R2(l[2])-m;m+=k;var q,t=q=void 0,v=void 0,y=void 0,B=l[3];l={textAlign:2};B=g.p(B?B.split(" "):[]);for(var C=B.next();!C.done;C=B.next())if(C=C.value.split(":"),2==C.length){var G=C[1];switch(C[0]){case "line":C=G.split(",");C[0].endsWith("%")&&(y=C[0],l.ug=Number.parseInt(y,10),2==C.length&&(v=C[1].trim()));break;case "position":C=G.split(",");
t=C[0];l.Ee=Number.parseInt(t,10);2==C.length&&(q=C[1].trim());break;case "align":switch(G){case "start":l.textAlign=0;break;case "middle":l.textAlign=2;break;case "end":l.textAlign=1}}}y||(l.ug=100,v||(v="end"));if(!t)switch(l.textAlign){case 0:l.Ee=0;break;case 1:l.Ee=100;break;default:l.Ee=50}t=0;switch(v){case "center":t+=3;break;case "end":t+=6;break;default:t+=0}switch(q){case "line-left":t+=0;break;case "center":t+=1;break;case "line-right":t+=2;break;default:switch(l.textAlign){case 0:t+=
0;break;case 2:t+=1;break;case 1:t+=2}}l.If=0>t||8<t?7:t;q=l;f=f.substring(h3.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");t=q;q=f;f={};if(0>q.indexOf("<")&&0>q.indexOf("&"))k=S2(m,n,5,t),n=new T1(m,n,5,k.id,q,!1,g.Zb(f)?void 0:f),c.push(k),c.push(n),g.H(k,n),k.g.push(n);else for(v=q.split(wpa),1==v.length?(q=5,t=S2(m,n,q,t)):(y=q=6,t=Object.assign({vl:32},t),t=new U1(m,n,y,"_"+V1++,t)),c.push(t),y=m,l=0;l<v.length;l++)B=v[l],0==l%2?(C=g.bZ("<html>"+B+"</html>"),C.getElementsByTagName("parsererror").length?
(G=C.createElement("span"),G.appendChild(C.createTextNode(B))):G=C.firstChild,Q2(this,y,n-(y-m),q,t,0<l,G,f,c)):y=R2(B)+k}h3.lastIndex=0}}return c};
var vpa=/^NOTE/,upa=/(?:\r\n|\r|\n){2,}/,h3=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),wpa=/<((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})>/;g.r(T2,g.F);T2.prototype.clear=function(){this.g&&this.g.dispose();this.g=null};
T2.prototype.reset=function(){this.g&&this.g.reset()};
T2.prototype.V=function(){this.clear();g.F.prototype.V.call(this)};g.r(W2,g.SO);g.h=W2.prototype;g.h.V=function(){if(this.u||this.D){var a=this.M.app.u;a&&a.Ui()}else g3(this,!1);g.SO.prototype.V.call(this)};
g.h.load=function(){g.SO.prototype.load.call(this);var a=!g.P(this.l.experiments,"web_player_captions_track_list_changed_killswitch");this.B=this.player.getAudioTrack();if(this.i)this.g&&(this.Y.clear(),this.u?b3(this,!0):3!=this.player.getPresentingPlayerType()&&this.i.Sp(this.g,"srv3",(0,g.x)(this.cK,this)),!a||this.u||this.D||a3(this)||this.player.ha("captionschanged",E1(this.g))),a||(this.g&&!a3(this)?this.player.ha("captionschanged",E1(this.g)):this.player.ha("onCaptionsTrackListChanged"));else{var b;
this.ca?b=new O1(this.O.ga,this.player):this.ua?b=new J1(this.l,this.O,this.player.getAudioTrack()):b=new R1(this.O.Si,this.O.videoId,this.O.Mf||this.l.Mf||g.gC(this.O,"yt:cc_default_lang")||this.l.Xb,this.O.xo,this.l);this.i=b;g.H(this,this.i);b.Tp((0,g.x)(this.bK,this))}};
g.h.unload=function(){this.u&&this.g?b3(this,!1):(this.da&&g.en(this.da),g.WP(this.player.app,"captions",void 0),this.G=[],this.i&&this.i.vg(),this.Y.clear(),this.C&&g.rK(this.player,this.C),this.Or());g.SO.prototype.unload.call(this);var a=g.S(this.player.app);a&&g.MH(a.u);this.player.ha("captionschanged",{})};
g.h.create=function(){(this.X?this.u||this.D:Y2(this)||X2(this))&&this.load()};
g.h.bK=function(){var a;this.I||X2(this)?a=$2(this,this.I):Y2(this)&&(a=Z2(this));if(this.u||this.D){for(var b=G1(this.i.i,!0),c=[],d=0;d<b.length;d++){var e=b[d],f={kind:"subtitles",label:g.zz(e),srclang:F1(e),id:e.toString()};this.D||(f.src=this.i.lj(e,"vtt"));e==a&&(f["default"]=1);c.push(g.Pd("TRACK",f))}a=this.M.app.u;a.Mi(c);c=a.Za();this.ka&&this.ba.J(c.textTracks,"change",this.dK)}else!this.g&&a&&d3(this,a),this.player.ha("onCaptionsTrackListChanged"),this.player.ha("onApiChange")};
g.h.dK=function(){for(var a=this.M.app.u.Za().textTracks,b=null,c=0;c<a.length;c++)if("showing"==a[c].mode)a:{b=a[c].id;var d=G1(this.i.i,!0);for(var e=0;e<d.length;e++)if(d[e].toString()==b){b=d[e];break a}b=null}(this.loaded?this.g:null)!=b&&d3(this,b,!0)};
g.h.FL=function(){!this.g&&this.u||this.unload()};
g.h.cK=function(a,b,c,d){if(a){this.i.ny()&&(this.G=[],g.WP(this.M.app,"captions",void 0),this.W.mj(),this.Y.reset());var e=this.Y;c=c||0;d=d||0;if("string"!==typeof a){var f=new DataView(a);if(8<=f.byteLength&&1718909296==f.getUint32(4)&&(f=g.hv(f,0,1835295092),a=a.slice(f.dataOffset,f.dataOffset+f.size),!M2(a))){a=new Uint8Array(a);f=[];for(var k=0,l=0;k<a.length;){var m=a[k++];if(128>m)f[l++]=String.fromCharCode(m);else if(191<m&&224>m){var n=a[k++];f[l++]=String.fromCharCode((m&31)<<6|n&63)}else if(239<
m&&365>m){n=a[k++];var q=a[k++],t=a[k++];m=((m&7)<<18|(n&63)<<12|(q&63)<<6|t&63)-65536;f[l++]=String.fromCharCode(55296+(m>>10));f[l++]=String.fromCharCode(56320+(m&1023))}else n=a[k++],q=a[k++],f[l++]=String.fromCharCode((m&15)<<12|(n&63)<<6|q&63)}a=f.join("")}}if(a)try{if("string"!==typeof a){var v=a,y=c,B=d;if(!M2(v))throw Error("Invalid binary caption track data");e.g||(e.g=new K2(B,b));var C=e.g.o(v,y)}else{if("WEBVTT"==a.substring(0,6)){b=a;y=c;e.g||(e.g=new P2);var G=e.g.o(b,y);.01>Math.random()&&
g.yo(Error("Deprecated subtitles format in web player: WebVTT"));v=G}else b:{G=a;y=g.bZ(G);if(!y||!y.firstChild){var I=Error("Invalid caption track data");I.params=G;throw I;}if("timedtext"==y.firstChild.tagName){if(3==parseInt(y.firstChild.getAttribute("format"),10)){if(!e.g){G={};if(B=F1(b))G.lang=B,spa.test(B)&&(G.pe=1);e.g=new x2(G,e.i)}v=e.g.o(y,c);break b}var E=Error("Unsupported subtitles format in web player (Format2)");E.params=G;throw E;}if("transcript"==y.firstChild.tagName){var M=Error("Unsupported subtitles format in web player (Format1)");
M.params=G;throw M;}var Y=Error("Invalid caption track data");Y.params=G;throw Y;}C=v}var ia=C}catch(Ia){g.N(Ia),e.clear(),ia=[]}else ia=[];g.rK(this.player,ia);!this.I||this.D||a3(this)||g.Zy(this.l)||g.$y(this.l)||(g.en(this.da),ia=W1({If:0,Ee:5,ug:5,ik:2,textAlign:0,pe:0,lang:"en"}),this.P=[ia],e=["Click "," for settings"],this.ma||(C=new g.ou(g.FL()),g.H(this,C),this.ma=C.element),C=ia.end-ia.start,(b=g.zz(this.g))&&this.P.push(new T1(ia.start,C,0,ia.id,b)),this.P.push(new T1(ia.start,C,0,ia.id,
e[0]),new T1(ia.start,C,0,ia.id,this.ma,!0),new T1(ia.start,C,0,ia.id,e[1],!0)),g.rK(this.player,this.P),g.cn(this.da));!this.I||this.D||a3(this)||(c3(this,"module-enabled",!0),this.B&&(this.B.g=this.g),(ia=g.S(this.player.app))&&g.MH(ia.u));this.I=!1}};
g.h.JD=function(a){this.G.push(a);this.W.mj()};
g.h.KD=function(a){g.eb(this.G,a);this.i instanceof O1&&this.i.w&&g.tS(this.player.app,[a],void 0);this.W.mj()};
g.h.PK=function(a){if(a instanceof U1){var b=this.R[a.id];b&&b.o!=a&&(b.dispose(),delete this.R[a.id],b=null);b||(b=rpa(this,a))&&(this.R[a.id]=b)}else b=a.windowId,this.S[b]||(this.S[b]=[]),this.S[b].push(a)};
g.h.VK=function(){f3(this,this.P);this.P=null};
g.h.Cz=function(){this.W.stop();g.$b(this.S);this.G.sort(g.tD);var a=this.G;if(this.C){var b=(0,g.Wd)(a,function(c){return-1==this.C.indexOf(c)},this);
b.length&&(a=b)}(0,g.z)(a,this.PK,this);g.Mb(this.R,function(c,d){this.S[d]?(c.element.parentNode||g.vK(this.player,c.element,4),c.lh(this.S[d])):(c.dispose(),delete this.R[d])},this)};
g.h.aL=function(){U2(this,{},!0);g.P(this.l.experiments,"web_player_disable_publish_captions_settings_changed_on_reset")||this.player.ha("captionssettingschanged")};
g.h.UB=function(){var a=e3.sb;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.De?3:a.bold?1:a.De?2:0,textOpacity:a.textOpacity,windowColor:e3.windowColor,windowOpacity:e3.windowOpacity};var b=V2(this,"display-settings")||{};null!=b.background&&(a.background=b.background);null!=b.backgroundOverride&&(a.backgroundOverride=b.backgroundOverride);null!=b.backgroundOpacity&&
(a.backgroundOpacity=b.backgroundOpacity);null!=b.backgroundOpacityOverride&&(a.backgroundOpacityOverride=b.backgroundOpacityOverride);null!=b.charEdgeStyle&&(a.charEdgeStyle=b.charEdgeStyle);null!=b.charEdgeStyleOverride&&(a.charEdgeStyleOverride=b.charEdgeStyleOverride);null!=b.color&&(a.color=b.color);null!=b.colorOverride&&(a.colorOverride=b.colorOverride);null!=b.fontFamily&&(a.fontFamily=b.fontFamily);null!=b.fontFamilyOverride&&(a.fontFamilyOverride=b.fontFamilyOverride);null!=b.fontSizeIncrement&&
(a.fontSizeIncrement=b.fontSizeIncrement);null!=b.fontSizeIncrementOverride&&(a.fontSizeIncrementOverride=b.fontSizeIncrementOverride);null!=b.fontStyle&&(a.fontStyle=b.fontStyle);null!=b.fontStyleOverride&&(a.fontStyleOverride=b.fontStyleOverride);null!=b.textOpacity&&(a.textOpacity=b.textOpacity);null!=b.textOpacityOverride&&(a.textOpacityOverride=b.textOpacityOverride);null!=b.windowColor&&(a.windowColor=b.windowColor);null!=b.windowColorOverride&&(a.windowColorOverride=b.windowColorOverride);
null!=b.windowOpacity&&(a.windowOpacity=b.windowOpacity);null!=b.windowOpacityOverride&&(a.windowOpacityOverride=b.windowOpacityOverride);return a};
g.h.Hz=function(a,b){var c={};g.Sa(c,V2(this,"display-settings"));g.Sa(c,a);U2(this,c,b);this.player.ha("captionssettingschanged")};
g.h.Or=function(){!this.u&&this.loaded&&(g.Mb(this.R,function(a,b){a.dispose();delete this.R[b]},this),this.Cz())};
g.h.qc=function(a,b){switch(a){case "fontSize":if(isNaN(b))break;var c=g.nd(b,-2,4);this.Hz({fontSizeIncrement:c});return c;case "reload":b&&!this.u&&d3(this,this.g,!0);break;case "stickyLoading":void 0!=b&&this.l.vb&&c3(this,"module-enabled",!!b);break;case "track":if(!this.i)return{};if(b){if(this.u)break;if(!g.Oa(b))break;if(g.Zb(b)){d3(this,null,!0);break}for(var d=G1(this.i.i,!0),e=0;e<d.length;e++){var f=d[e];f.i!=b.languageCode||c&&f.l!=b.languageName||(c=b.translationLanguage?$oa(f,b.translationLanguage):
f)}!c||c==this.g&&this.loaded||d3(this,c,!0)}else return this.loaded&&this.g&&!a3(this)?E1(this.g):{};return"";case "tracklist":return this.i?(0,g.fe)(G1(this.i.i,!(!b||!b.includeAsr)),function(k){return E1(k)}):[];
case "translationLanguages":return this.i?this.i.u.map(function(k){return Object.assign({},k)}):[];
case "sampleSubtitles":this.u||void 0==b||g3(this,!!b)}};
g.h.getOptions=function(){var a="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.l.vb&&a.push("stickyLoading");return a};
g.h.ID=function(){var a=this.g;return a?{cc:a.w}:{}};
g.h.zL=function(){this.loaded&&this.g&&!a3(this)?(c3(this,"module-enabled",!1),this.unload(),Y2(this,!0)&&d3(this,Z2(this),!1)):d3(this,a3(this)||!this.g?$2(this,!0):this.g,!0)};
g.h.VG=function(){var a=a3(this);Y2(this,a)?d3(this,this.player.getAudioTrack().Fl,!1):this.O.captionTracks.length&&(this.loaded&&this.unload(),(this.X?this.u||this.D:Y2(this)||X2(this))&&(a?d3(this,$2(this),!1):this.load()))};g.fP.captions=W2;})(_yt_player);
