(function(g){var window=this;var j3=function(a,b,c){var d=b.ra();g.L(a.element,"ytp-suggestion-set",!!d.videoId);var e=b.getPlaylistId();c=b.dc(c?c:"mqdefault.jpg");var f=b instanceof g.FB&&b.lengthSeconds?g.cL(b.lengthSeconds):null,k=!!e;e=k&&"RD"==(new g.vD(e.substr(0,2),e.substr(2))).type;var l=b instanceof g.FB?b.na:null;d={title:b.title,author:b.author,author_and_views:d.shortViewCount?b.author+" \u2022 "+d.shortViewCount:b.author,aria_label:b.Ni||g.NL("Watch $TITLE",{TITLE:b.title}),duration:f,url:b.Ih(),is_live:l,is_list:k,
is_mix:e,background:c?"background-image: url("+c+")":""};b instanceof g.xD&&(d.playlist_length=b.getLength());a.update(d)},k3=function(a,b){g.vu.call(this,{A:"div",
U:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.player=a;this.created=!1},l3=function(a){g.T.call(this,{A:"div",
U:["ytp-upnext","ytp-player-content"],K:{"aria-label":"{{aria_label}}"},H:[{A:"div",F:"ytp-cued-thumbnail-overlay-image",K:{style:"{{background}}"}},{A:"span",F:"ytp-upnext-top",H:[{A:"span",F:"ytp-upnext-header",T:"Up Next"},{A:"span",F:"ytp-upnext-title",T:"{{title}}"},{A:"span",F:"ytp-upnext-author",T:"{{author}}"}]},{A:"a",F:"ytp-upnext-autoplay-icon",K:{role:"button",href:"{{url}}","aria-label":"Play next video"},H:[{A:"svg",K:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},H:[{A:"circle",
F:"ytp-svg-autoplay-circle",K:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{A:"circle",F:"ytp-svg-autoplay-ring",K:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{A:"path",F:"ytp-svg-fill",K:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{A:"span",F:"ytp-upnext-bottom",H:[{A:"span",F:"ytp-upnext-cancel"},{A:"span",F:"ytp-upnext-paused",T:"Autoplay is paused"}]}]});
this.w=null;var b=this.i["ytp-upnext-cancel"];this.w=new g.T({A:"button",U:["ytp-upnext-cancel-button","ytp-button"],K:{tabindex:"0","aria-label":"Cancel autoplay"},T:"Cancel"});g.H(this,this.w);this.w.ea("click",this.aH,this);this.w.g(b);this.l=a;this.I=this.i["ytp-svg-autoplay-ring"];this.C=this.B=this.o=this.u=null;this.D=new g.J(this.ul,5E3,this);g.H(this,this.D);this.G=0;this.J(this.i["ytp-upnext-autoplay-icon"],"click",this.NI);this.rx();this.J(a,"autonavvisibility",this.rx);this.J(a,"mdxnowautoplaying",
this.fI);this.J(a,"mdxautoplaycanceled",this.gI);this.J(a,"mdxautoplayupnext",this.Gz);3==this.l.getPresentingPlayerType()&&(a=(a=g.fK(g.ZJ(this.l)))?a.SB():null)&&this.Gz(a)},m3=function(a,b){if(!a.o){g.No("a11y-announce","Up Next "+a.u.title);
a.G=(0,g.Mq)();a.o=new g.J((0,g.x)(a.mo,a,b),25);a.mo(b);var c=b||g.Q(a.l.L().experiments,"autoplay_time")||1E4;a.l.ha("onAutonavCoundownStarted",c)}g.mn(a.element,"ytp-upnext-autoplay-paused")},o3=function(a){n3(a);
a.G=(0,g.Mq)();a.mo();g.K(a.element,"ytp-upnext-autoplay-paused")},n3=function(a){a.o&&(a.o.dispose(),a.o=null)},p3=function(a,b){b=void 0===b?!1:b;
if(g.P(a.l.L().experiments,"autonav_notifications")&&b&&window.Notification&&document.hasFocus){var c=Notification.permission;"default"==c?Notification.requestPermission():"granted"!=c||document.hasFocus()||(c=a.u.ra(),a.ul(),a.B=new Notification("Up Next",{body:c.title,icon:c.dc()}),a.C=a.J(a.B,"click",a.DI),a.D.start())}n3(a);a.l.nextVideo(!1,b)},q3=function(a){k3.call(this,a,"subscribecard-endscreen");
var b=a.getVideoData();this.l=new g.T({A:"div",F:"ytp-subscribe-card",H:[{A:"img",F:"ytp-author-image",K:{src:b.Od}},{A:"div",F:"ytp-subscribe-card-right",H:[{A:"div",F:"ytp-author-name",T:b.author},{A:"div",F:"html5-subscribe-button-container"}]}]});g.H(this,this.l);this.l.g(this.element);this.o=new g.bQ("Subscribe",null,"Unsubscribe",null,!0,!1,b.Ef,b.subscribed,"trailer-endscreen",null,null,a);g.H(this,this.o);this.o.g(this.l.i["html5-subscribe-button-container"]);this.hide()},r3=function(a){var b=
a.L(),c=g.Ds||g.ag?{style:"will-change: opacity"}:void 0,d=b.i,e=["ytp-videowall-still"];
b.g&&e.push("ytp-videowall-show-text");g.T.call(this,{A:"a",U:e,K:{href:"{{url}}",target:d?b.u:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},H:[{A:"div",F:"ytp-videowall-still-image",K:{style:"{{background}}"}},{A:"span",F:"ytp-videowall-still-info",H:[{A:"span",F:"ytp-videowall-still-info-bg",H:[{A:"span",F:"ytp-videowall-still-info-content",K:c,H:[{A:"span",F:"ytp-videowall-still-info-title",T:"{{title}}"},{A:"span",F:"ytp-videowall-still-info-author",
T:"{{author_and_views}}"},{A:"span",F:"ytp-videowall-still-info-live",T:"Live"},{A:"span",F:"ytp-videowall-still-info-duration",T:"{{duration}}"}]}]}]},{A:"span",U:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],H:[{A:"span",F:"ytp-videowall-still-listlabel-icon"},"Playlist",{A:"span",F:"ytp-videowall-still-listlabel-length",H:[" (",{A:"span",T:"{{playlist_length}}"},")"]}]},{A:"span",U:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],H:[{A:"span",F:"ytp-videowall-still-listlabel-mix-icon"},
"Mix",{A:"span",F:"ytp-videowall-still-listlabel-length",T:" (50+)"}]}]});this.w=d;this.l=a;this.o=null;this.u=new g.Ks(this);g.H(this,this.u);this.ea("click",this.C);this.ea("keypress",this.D);this.u.J(a,"videodatachange",this.B);g.yK(a,this.element,this);this.B()},s3=function(a){g.AK(a.l,a.element);
var b=a.o.ra().videoId,c=a.o.getPlaylistId();g.rS(a.l.app,b,a.o.Cb,c,void 0,void 0)},t3=function(a){k3.call(this,a,"videowall-endscreen");
this.B=a;this.w=0;this.o=[];this.C=this.O=this.u=null;this.D=this.P=!1;this.M=null;this.ba=new g.Ks(this);g.H(this,this.ba);this.G=new g.J(g.Ra(g.K,this.element,"ytp-show-tiles"),0);g.H(this,this.G);var b=new g.T({A:"button",U:["ytp-button","ytp-endscreen-previous"],K:{"aria-label":"Previous"},H:[g.kL()]});g.H(this,b);b.g(this.element);b.ea("click",this.sE,this);this.I=new g.ou({A:"div",F:"ytp-endscreen-content"});g.H(this,this.I);this.I.g(this.element);b=new g.T({A:"button",U:["ytp-button","ytp-endscreen-next"],
K:{"aria-label":"Next"},H:[g.lL()]});g.H(this,b);b.g(this.element);b.ea("click",this.rE,this);this.l=new l3(a);g.H(this,this.l);g.vK(this.player,this.l.element,4);this.hide()},u3=function(a){return g.wK(a.player)&&a.ot()&&!a.C},v3=function(a,b){return(0,g.fe)(b.suggestions,function(c){c=g.OL(a.B.L(),c);
g.H(a,c);return c})},w3=function(a){var b=a.iq();
b!=a.P&&(a.P=b,a.player.N("autonavvisibility"))},y3=function(a){g.SO.call(this,a);
this.g=null;this.i=new g.Ks(this);g.H(this,this.i);this.l=a.L();x3(a)?this.g=new t3(this.player):this.l.Pa?this.g=new q3(this.player):this.g=new k3(this.player);g.H(this,this.g);g.vK(this.player,this.g.element,4);this.My();this.i.J(a,"videodatachange",this.My,this);this.i.J(a,g.uD("endscreen"),this.AD,this);this.i.J(a,"crx_endscreen",this.BD,this)},x3=function(a){a=a.L();
return a.La&&!a.Pa};
g.r(k3,g.vu);k3.prototype.create=function(){this.created=!0};
k3.prototype.destroy=function(){this.created=!1};
k3.prototype.ot=function(){return!1};
k3.prototype.iq=function(){return!1};g.r(l3,g.T);g.h=l3.prototype;g.h.ul=function(){this.B&&(this.D.stop(),this.Sa(this.C),this.C=null,this.B.close(),this.B=null)};
g.h.rx=function(){g.uu(this,g.$J(this.l))};
g.h.DI=function(){window.focus();this.ul()};
g.h.hide=function(){g.T.prototype.hide.call(this)};
g.h.mo=function(a){a=a||g.Q(this.l.L().experiments,"autoplay_time")||1E4;var b=Math.min((0,g.Mq)()-this.G,a);a=Math.min(b/a,1);this.I.setAttribute("stroke-dashoffset",-211*(a+1));1<=a&&3!=this.l.getPresentingPlayerType()?p3(this,!0):this.o&&this.o.start()};
g.h.NI=function(a){!g.Zd(this.w.element,g.br(a))&&g.VL(a,this.l)&&p3(this)};
g.h.aH=function(){g.bK(this.l,!0)};
g.h.fI=function(a){this.l.getPresentingPlayerType();this.show();m3(this,a)};
g.h.Gz=function(a){this.l.getPresentingPlayerType();this.u&&this.u.ra().videoId==a.ra().videoId||(this.u=a,j3(this,a,"hqdefault.jpg"))};
g.h.gI=function(){this.l.getPresentingPlayerType();n3(this);this.hide()};
g.h.V=function(){n3(this);this.ul();g.T.prototype.V.call(this)};g.r(q3,k3);g.r(r3,g.T);r3.prototype.C=function(a){g.VL(a,this.l,this.w,this.o.Cb||void 0)&&s3(this)};
r3.prototype.D=function(a){switch(a.keyCode){case 13:case 32:g.gr(a)||(s3(this),g.fr(a))}};
r3.prototype.B=function(){var a=this.l.getVideoData(),b=this.l.L();this.w=a.Vb?!1:b.i};g.r(t3,k3);g.h=t3.prototype;g.h.create=function(){k3.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.u=v3(this,a),this.O=a);this.Cf();this.ba.J(this.player,"appresize",this.Cf);this.ba.J(this.player,"onVideoAreaChange",this.Cf);this.ba.J(this.player,"videodatachange",this.tE);this.ba.J(this.player,"autonavchange",this.jq);this.ba.J(this.player,"autonavcancel",this.qE);a=this.O.autonavState;a!=this.M&&this.jq(a);this.ba.J(this.element,"transitionend",this.eK)};
g.h.destroy=function(){g.Ms(this.ba);g.Ei(this.o);this.o=[];this.u=null;k3.prototype.destroy.call(this);g.mn(this.element,"ytp-show-tiles");this.G.stop();this.M=this.O.autonavState};
g.h.ot=function(){return 1!=this.O.autonavState};
g.h.show=function(){k3.prototype.show.call(this);g.mn(this.element,"ytp-show-tiles");this.player.L().g?g.dn(this.G):this.G.start();(this.D||this.C&&this.C!=this.O.clientPlaybackNonce)&&g.bK(this.player,!1);u3(this)?(w3(this),2==this.O.autonavState?g.P(this.player.L().experiments,"fast_autonav_in_background")&&3==this.player.getVisibilityState()?p3(this.l,!0):m3(this.l):3==this.O.autonavState&&o3(this.l)):(g.bK(this.player,!0),w3(this))};
g.h.hide=function(){k3.prototype.hide.call(this);o3(this.l);w3(this)};
g.h.eK=function(a){g.br(a)==this.element&&this.Cf()};
g.h.Cf=function(){if(this.u&&this.u.length){g.K(this.element,"ytp-endscreen-paginate");var a=g.mK(this.B,!0,this.B.isFullscreen()),b=g.LC(this.B);b&&(b=b.Ub()?48:32,a.width-=2*b);var c=a.width/a.height,d=96/54,e=b=2,f=Math.max(a.width/96,2),k=Math.max(a.height/54,2),l=this.u.length,m=Math.pow(2,2);var n=l*m+(Math.pow(2,2)-m);n+=Math.pow(2,2)-m;for(n-=m;0<n&&(b<f||e<k);){var q=b/2,t=e/2,v=b<=f-2&&n>=t*m,y=e<=k-2&&n>=q*m;if((q+1)/t*d/c>c/(q/(t+1)*d)&&y)n-=q*m,e+=2;else if(v)n-=t*m,b+=2;else if(y)n-=
q*m,e+=2;else break}d=!1;n>=3*m&&6>=l*m-n&&(4<=e||4<=b)&&(d=!0);m=96*b;n=54*e;c=m/n<c?a.height/n:a.width/m;c=Math.min(c,2);m*=c;n*=c;m*=g.nd(a.width/m||1,1,1.21);n*=g.nd(a.height/n||1,1,1.21);m=Math.floor(Math.min(a.width,m));n=Math.floor(Math.min(a.height,n));a=this.I.element;g.sg(a,m,n);g.Yf(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});c=this.l;f=this.u[0];c.u=f;j3(c,f,"hqdefault.jpg");g.L(this.element,"ytp-endscreen-takeover",u3(this));w3(this);m+=4;n+=4;for(f=c=0;f<b;f++)for(k=0;k<e;k++)if(q=
c,t=0,d&&f>=b-2&&k>=e-2?t=1:0==k%2&&0==f%2&&(2>k&&2>f?0==k&&0==f&&(t=2):t=2),q=g.od(q+this.w,l),0!=t){v=this.o[c];v||(v=new r3(this.player),this.o[c]=v,a.appendChild(v.element));y=Math.floor(n*k/e);var B=Math.floor(m*f/b),C=Math.floor(n*(k+t)/e)-y-4,G=Math.floor(m*(f+t)/b)-B-4;g.hg(v.element,B,y);g.sg(v.element,G,C);g.Yf(v.element,"transitionDelay",(k+f)/20+"s");g.L(v.element,"ytp-videowall-still-mini",1==t);g.L(v.element,"ytp-videowall-still-large",2<t);t=v;q=this.u[q];t.o!=q&&(t.o=q,j3(t,q,g.kn(t.element,
"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg"),(q=(q=q.Cb)&&q.itct)&&g.zK(t.l,t.element,q));c++}g.L(this.element,"ytp-endscreen-paginate",c<l);for(b=this.o.length-1;b>=c;b--)e=this.o[b],g.Vd(e.element),g.Di(e);this.o.length=c}};
g.h.tE=function(){var a=this.player.getVideoData();this.O!=a&&(this.w=0,this.u=v3(this,a),this.O=a,this.Cf())};
g.h.rE=function(){this.w+=this.o.length;this.Cf()};
g.h.sE=function(){this.w-=this.o.length;this.Cf()};
g.h.TC=function(){return!!this.l.o};
g.h.jq=function(a){1==a?(this.D=!1,this.C=this.O.clientPlaybackNonce,n3(this.l),this.Da()&&this.Cf()):(this.D=!0,this.Da()&&u3(this)&&(2==a?m3(this.l):3==a&&o3(this.l)))};
g.h.qE=function(a){if(a){for(a=0;a<this.o.length;a++)g.BK(this.B,this.o[a].element,!0);this.jq(1)}else this.C=null,this.D=!1;this.Cf()};
g.h.iq=function(){return this.Da()&&u3(this)};g.r(y3,g.SO);g.h=y3.prototype;g.h.dw=function(){var a=this.player.getVideoData(),b=!!(a&&a.suggestions&&a.suggestions.length);b=!x3(this.player)||b;a=a.sh||g.Uy(a.Ma);var c=g.MR(this.player.app);return b&&!a&&!c};
g.h.cw=function(){return this.g.iq()};
g.h.MC=function(){return this.cw()?this.g.TC():!1};
g.h.V=function(){g.WP(this.player.app,"endscreen",void 0);g.SO.prototype.V.call(this)};
g.h.load=function(){g.SO.prototype.load.call(this);this.g.show()};
g.h.unload=function(){g.SO.prototype.unload.call(this);this.g.hide();this.g.destroy()};
g.h.AD=function(a){this.dw()&&(this.g.created||this.g.create(),"load"==a.getId()&&this.load())};
g.h.BD=function(a){"load"==a.getId()&&this.loaded&&this.unload()};
g.h.My=function(){g.WP(this.player.app,"endscreen",void 0);var a=this.player.getVideoData();a=new g.rD(Math.max(1E3*(a.lengthSeconds-10),0),0x8000000000000,{id:"preload",namespace:"endscreen"});g.H(this,a);var b=new g.rD(0x8000000000000,0x8000000000000,{id:"load",priority:6,namespace:"endscreen"});g.H(this,b);g.rK(this.player,[a,b])};g.fP.endscreen=y3;})(_yt_player);
